### ISSUE TITLE
Unable to write to /KEK-T2K/

### ISSUE THREAD

**Issue by hastingskek** [goiwai/irods-decommissioning-2024#1]
Today we (T2K near detector data quality and calibration people) discovered that
the automated jobs uploading data to the KEK iRODS have been failing since The
evening of 2024-05-28. Eg.
```
[irodsdq@soffdata02 ~]$ iput test.txt
ERROR: putUtil: put error for /KEK-T2K/home/dataquality/data/test.txt, status =
-526013 status = -526013 UNIX_FILE_GET_FS_FREESPACE_ERR, Permission denied
```
T2K run 13 is scheduled to continue  until the start of the next month. We had been
under the impression that we could use iRODs until then.

**Comment by goiwai** [comment]
Let me propose two possible solutions:

1. Roll back the zone KEK-T2K to access by iRODS client utilities by the end of Run 13 (approx. beginning of July 2024)
2. [Permit write access to specific user DN to an alternative access point for the zone: KEK-T2K]( https://github.com/goiwai/irods-decommissioning-2024#alternative-access-points-for-the-zone-kek-t2k)

Please let me know which solution you and your team prefer.

**Comment by hastingskek** [comment]
We prefer option 1. since it seems option 2. would require extreme changes to automated workflows and as such is not appropriate for a very short term fix.

Please note that Run 13 in principle could continue until as late at July 8th and that we would want to be able still write data to iRODS until around 1 week after the run stops. So could you please keep it writable until at least July 15th?

**Comment by goiwai** [comment]
I have restored the ownership of the Zone KEK-T2K (hpssResc). I believe the data transfers run again as you did. I will keep the ownership until it is no longer necessary.
If the issue remains, please let me know with a minimum code snippet so I can reproduce the problem. [Good enough what you posted earlier](#issue-2342869887).

Please note that the iRODS decommissioning and replacement with *StoRM Storage Element* is not a measure without consent. I had an agreement with T2K people about the matter a year ago.

**Comment by NickHastings** [comment]
> I have restored the ownership of the Zone KEK-T2K (hpssResc). I believe the data transfers run again as you did. I will keep the ownership until it is no longer necessary. If the issue remains, please let me know with a minimum code snippet so I can reproduce the problem. [Good enough what you posted earlier](#issue-2342869887).

I can confirm that it is working now. Thanks for restoring it so quickly.

 
> Please note that the iRODS decommissioning and replacement with _StoRM Storage Element_ is not a measure without consent. I had an agreement with T2K people about the matter a year ago.

We were completely aware of the decommissioning but had (at least I had) been informed that the iRODS system would still be available for the T2K run prior to the J-PARC Summer maintenance period in 2024.

**Comment by goiwai** [comment]
> > I have restored the ownership of the Zone KEK-T2K (hpssResc). I believe the data transfers run again as you did. I will keep the ownership until it is no longer necessary. If the issue remains, please let me know with a minimum code snippet so I can reproduce the problem. [Good enough what you posted earlier](#issue-2342869887).
> 
> I can confirm that it is working now. Thanks for restoring it so quickly.

It's good to hear that. I would keep the issue open until read-only mode as KEK-T2K again.

> > Please note that the iRODS decommissioning and replacement with _StoRM Storage Element_ is not a measure without consent. I had an agreement with T2K people about the matter a year ago.
> 
> We were completely aware of the decommissioning but had (at least I had) been informed that the iRODS system would still be available for the T2K run prior to the J-PARC Summer maintenance period in 2024.

You are perfectly correct. To be more precise, the iRODS system will keep running in **read-only mode** by the end of August 2024.

**Comment by NickHastings** [comment]
The problem was I as not aware of *when* the transition to read only mode would happen. I was certainly under the impression it would not be in May. Thanks for restoring it.

**Comment by goiwai** [comment]
@NickHastings I would like to turn the Zone KEK-T2K (hpssResc) on read-only mode again before the summer maintenance week of KEKCC. Please let me know the date that is most convenient for you. If you have no specific preference, I will do it on Thursday, 31st July 2024.

**Comment by hastingskek** [comment]
@goiwai  I have no preference. Please go ahead a do it whenever suits you.

**Comment by goiwai** [comment]
The Zone KEK-T2K is now read-only and no longer writable.
